{
  "id": "omarchy",
  "name": "Omarchy",
  "displayName": "Omarchy (System)",
  "isDark": true,
  "bg": {
    "app": "{{ background }}",
    "panel": "{{ dark_background }}",
    "panelAlt": "{{ darker_background }}",
    "input": "{{ mix background foreground 8% }}",
    "selected": "{{ selection }}",
    "selectedAlt": "{{ mix background selection 50% }}",
    "highlight": "{{ mix background foreground 12% }}",
    "codeBlock": "{{ dark_background }}",
    "codeBlockHeader": "{{ mix dark_background foreground 10% }}",
    "badge": "{{ mix background foreground 15% }}",
    "badgeActive": "{{ mix background accent 25% }}",
    "aiBanner": "{{ mix background magenta 15% }}",
    "aiBannerSelected": "{{ mix background magenta 30% }}",
    "aiPrompt": "{{ mix background magenta 20% }}",
    "aiProposal": "{{ mix background yellow 15% }}",
    "buttonPrimary": "{{ accent }}",
    "buttonSecondary": "{{ mix background foreground 10% }}",
    "buttonDanger": "{{ red }}",
    "buttonSuccess": "{{ green }}",
    "buttonAi": "{{ magenta }}"
  },
  "border": {
    "subtle": "{{ mix background foreground 15% }}",
    "default": "{{ muted }}",
    "strong": "{{ mix background foreground 35% }}",
    "focus": "{{ accent }}",
    "info": "{{ cyan }}",
    "ai": "{{ magenta }}",
    "aiDeep": "{{ mix background magenta 40% }}",
    "success": "{{ green }}",
    "error": "{{ red }}"
  },
  "text": {
    "primary": "{{ foreground }}",
    "secondary": "{{ light_foreground }}",
    "muted": "{{ muted }}",
    "dim": "{{ dark_foreground }}",
    "faint": "{{ mix background foreground 30% }}",
    "inverse": "{{ background }}",
    "highlight": "{{ bright_foreground }}",
    "warning": "{{ yellow }}",
    "success": "{{ green }}",
    "error": "{{ red }}",
    "ai": "{{ magenta }}",
    "link": "{{ blue }}"
  },
  "accent": {
    "primary": "{{ accent }}",
    "primaryLight": "{{ mix accent foreground 30% }}",
    "secondary": "{{ cyan }}",
    "cyan": "{{ cyan }}",
    "purple": "{{ magenta }}",
    "purpleDark": "{{ mix background magenta 40% }}",
    "purpleLight": "{{ mix magenta foreground 30% }}",
    "green": "{{ green }}",
    "greenDark": "{{ mix background green 50% }}",
    "red": "{{ red }}",
    "redDark": "{{ mix background red 50% }}",
    "yellow": "{{ yellow }}",
    "blue": "{{ blue }}",
    "blueDark": "{{ mix background blue 50% }}"
  },
  "status": {
    "todo": "{{ muted }}",
    "inProgress": "{{ cyan }}",
    "urgent": "{{ red }}",
    "question": "{{ magenta }}",
    "paused": "{{ dark_foreground }}",
    "cancelled": "{{ dark_foreground }}",
    "done": "{{ green }}",
    "priorityHigh": "{{ red }}",
    "priorityMedium": "{{ yellow }}",
    "priorityLow": "{{ blue }}"
  },
  "syntax": {
    "h1": "{{ accent }}",
    "h2": "{{ cyan }}",
    "h3": "{{ magenta }}",
    "h4": "{{ green }}",
    "bold": "{{ bright_foreground }}",
    "italic": "{{ light_foreground }}",
    "code": "{{ red }}",
    "codeBg": "{{ mix background foreground 8% }}",
    "link": "{{ blue }}",
    "list": "{{ muted }}",
    "quote": "{{ muted }}",
    "table": "{{ foreground }}",
    "keyword": "{{ magenta }}",
    "string": "{{ green }}",
    "stringSpecial": "{{ cyan }}",
    "number": "{{ cyan }}",
    "comment": "{{ muted }}",
    "constant": "{{ yellow }}",
    "function": "{{ blue }}",
    "type": "{{ yellow }}",
    "tag": "{{ red }}",
    "attribute": "{{ yellow }}",
    "parameter": "{{ foreground }}",
    "punctuation": "{{ dark_foreground }}",
    "default": "{{ foreground }}"
  }
}
